spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 解决Date返回值的格式问题
  datasource:
    username: xuqiang
    password: xq85782621.
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://118.89.165.37:3306/my_system_01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.meizhi.model ,com.meizhi.entity.request , com.meizhi.entity.response


server:
  port: 8090


logging:
  file: D:\\controller.log
  level:
    com.meizhi.mapper: debug

