spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 解决Date返回值的格式问题
  datasource:
    username: root
    password: Xq85782621.
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://139.196.161.252:3306/my_system_01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.meizhi.model ,com.meizhi.entity.request , com.meizhi.entity.response


server:
  port: 8090
  address: 0.0.0.0


