spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 解决Date返回值的格式问题
  datasource:
    username: root
    password: 123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/jpa-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123

mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.meizhi.model ,com.meizhi.entity.request , com.meizhi.entity.response


server:
  port: 8081


logging:
  file: D:\\controller.log
  level:
    com.meizhi.mapper: debug

